locales:
  fkv:
    name: Kven language Keyboards
    description: >-
      Mobile OS keyboards for the Kven language language from the Divvun group
      at UiT.
  en:
    name: Kven language Keyboards
    description: >-
      Mobile OS keyboards for the Kven language language from the Divvun group
      at UiT.
  nb:
    name: Kven language tastatur
    description: Mobiltastatur for Kven language fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
